nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        components:
            securitySchemes:
                SystemToken:
                    type: apiKey
                    in: header
                    name: X-TOKEN-SYSTEM
        security:
            -   SystemToken: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

